import Image from "next/image";
import { ArrowRight, Play } from "lucide-react";

const instagramUrl = "https://instagram.com/floo_fashionn";
const feed = {
  reel: { image: "/images/products/5.jpg", label: "New Collection", title: "The Art of Elegance" },
  posts: [
    { image: "/images/products/3.jpg", label: "Detail payet" }, { image: "/images/products/4.jpg", label: "Koleksi Floo" },
    { image: "/images/products/2.jpg", label: "Behind the craft" }, { image: "/images/products/1.jpg", label: "Floo girl" },
  ],
};
const InstagramIcon = ({ className = "" }: { className?: string }) => <svg className={className} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="5" /><circle cx="12" cy="12" r="4" /><circle cx="17.5" cy="6.5" r="0.8" fill="currentColor" /></svg>;

function FeedPost({ image, label }: { image: string; label: string }) {
  return <a href={instagramUrl} target="_blank" rel="noreferrer" className="group relative min-h-[190px] overflow-hidden rounded-2xl bg-[#d8c5b3] sm:min-h-[215px]"><Image src={image} alt={label} fill sizes="(max-width: 768px) 50vw, 20vw" className="object-cover transition duration-700 group-hover:scale-105" /><span className="absolute inset-0 bg-[#2d241f]/45 opacity-0 transition group-hover:opacity-100" /><span className="absolute left-4 top-4 text-white"><InstagramIcon className="size-4 drop-shadow" /></span><span className="absolute inset-x-4 bottom-4 translate-y-3 text-xs text-white opacity-0 transition group-hover:translate-y-0 group-hover:opacity-100">View on Instagram <ArrowRight className="ml-1 inline size-3" /></span></a>;
}

export default function Instagram() {
  return <section className="overflow-hidden bg-[#fffdfa]"><div className="container-custom py-14 md:py-20"><header className="flex flex-wrap items-end justify-between gap-5"><div><p className="text-xs uppercase tracking-[.31em] text-[#a07750]">Daily Floo</p><h2 className="mt-3 font-luxury text-4xl leading-none text-[#2d241f] md:text-5xl">Follow Our Story</h2><p className="mt-4 max-w-xl text-sm leading-7 text-[#6a594d]">See our latest looks, behind the scenes, and daily inspirations from Floo Fashion.</p></div><a href={instagramUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-3 border border-[#caa780] px-5 py-3 text-xs font-medium text-[#503b2e] transition hover:bg-[#b88a55] hover:text-white"><InstagramIcon className="size-4" />@floo_fashionn <ArrowRight className="ml-2 size-4" /></a></header><div className="mt-10 border-t border-[#eadfd4] pt-6"><div className="grid gap-4 md:grid-cols-[minmax(250px,.9fr)_minmax(0,1.3fr)]"><a href={instagramUrl} target="_blank" rel="noreferrer" className="group relative min-h-[430px] overflow-hidden rounded-2xl bg-[#d2b89b]"><Image src={feed.reel.image} alt={feed.reel.title} fill sizes="(max-width: 768px) 100vw, 35vw" className="object-cover transition duration-700 group-hover:scale-105" /><span className="absolute inset-0 bg-gradient-to-t from-[#211712]/85 via-transparent to-[#211712]/15" /><span className="absolute left-4 top-4 inline-flex items-center gap-2 rounded-full bg-black/25 px-3 py-1.5 text-xs text-white backdrop-blur"><InstagramIcon className="size-3.5" />REEL</span><span className="absolute left-1/2 top-1/2 flex size-16 -translate-x-1/2 -translate-y-1/2 items-center justify-center rounded-full border-2 border-white text-white transition group-hover:scale-110"><Play className="ml-1 size-7 fill-current" /></span><span className="absolute inset-x-5 bottom-5 text-white"><small className="text-xs">{feed.reel.label}</small><strong className="mt-1 block font-luxury text-2xl italic">{feed.reel.title}</strong><small className="mt-3 block text-white/85">View on Instagram</small></span></a><div className="grid grid-cols-2 gap-4">{feed.posts.map((post) => <FeedPost key={post.image} {...post} />)}</div></div></div><a href={instagramUrl} target="_blank" rel="noreferrer" className="mt-8 flex items-center justify-center gap-3 text-sm text-[#75533b] underline decoration-[#caa780] underline-offset-8 transition hover:text-[#b88a55]">Lihat lebih banyak di Instagram <ArrowRight className="size-4" /></a></div></section>;
}
