module.exports = {
  OWNER: "OWNER",
  ADMIN: "ADMIN",
  MANAGER: "MANAGER",
  CUSTOMER_SERVICE: "CUSTOMER_SERVICE",
  WAREHOUSE: "WAREHOUSE",
  PACKING: "PACKING",
  FINANCE: "FINANCE",
  MARKETING: "MARKETING",
};
